'use client';
import {useEffect,useState} from 'react';
import {X,Route,Clock3,ArrowUpRight,Check,BookmarkCheck,QrCode,Mountain,Save,Trash2} from 'lucide-react';
import type {Course,Visit} from './trail-types';
import {duration} from './trail-types';
function Elevation({course}:{course:Course}){
 const p=course.elevation;if(p.length<2)return <p className="missing-info">원본에 고도 데이터가 제공되지 않습니다.</p>;
 const low=Math.min(...p.map(p=>p[1])),high=Math.max(...p.map(p=>p[1])),min=Math.floor(Math.min(0,low)/20)*20,max=Math.max(20,Math.ceil(high/20)*20),distance=p.at(-1)![0];
 const xy=p.map(([d,e])=>[38+d/Math.max(distance,.01)*350,150-(e-min)/(max-min)*120]);
 const path=xy.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`).join(' '),area=`${path} L388,150 L38,150 Z`;
 return <><div className="elevation-stats"><span>최저 <b>{Math.round(low)} m</b></span><span>최고 <b>{Math.round(high)} m</b></span></div><svg className="elevation" viewBox="0 0 420 185" role="img" aria-label={`${course.name} 고도 그래프. 최저 ${Math.round(low)}미터, 최고 ${Math.round(high)}미터. GPX 표본 거리 ${distance.toFixed(1)}킬로미터.`}><path d={area} fill="#087d911a"/><path d={path} fill="none" stroke="#087d91" strokeWidth="2"/>{[min,Math.round((min+max)/2),max].map((v,i)=><g key={i}><line x1="38" x2="388" y1={150-(v-min)/(max-min)*120} y2={150-(v-min)/(max-min)*120} stroke="#ccdce0" strokeDasharray="3 4"/><text x="31" y={154-(v-min)/(max-min)*120} textAnchor="end">{v}</text></g>)}<text x="38" y="173">0 km</text><text x="388" y="173" textAnchor="end">{distance.toFixed(1)} km</text><text x="7" y="17">m</text></svg><p className="small-note">GPX 표본 기준입니다. 표기 코스 거리와 차이가 있을 수 있습니다.</p></>;
}
export function CourseDetail({course,visit,available,onSave,onRemove,onClose}:{course:Course;visit?:Visit;available:boolean;onSave:(c:Course,date:string,note:string)=>Promise<void>;onRemove:(c:Course)=>Promise<void>;onClose:()=>void}){
 const [date,setDate]=useState(visit?.visitedOn||''),[note,setNote]=useState(visit?.note||''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[failed,setFailed]=useState(false);
 useEffect(()=>{setDate(visit?.visitedOn||'');setNote(visit?.note||'')},[visit?.visitedOn,visit?.note]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');setFailed(false);try{await onSave(course,date,note);setMessage('계정에 저장했습니다.')}catch(e){setMessage(e instanceof Error?e.message:'저장하지 못했습니다.');setFailed(true)}finally{setBusy(false)}}
 async function remove(){setBusy(true);setMessage('');setFailed(false);try{await onRemove(course);setDate('');setNote('');setMessage('다녀온 코스 기록을 삭제했습니다.')}catch(e){setMessage(e instanceof Error?e.message:'삭제하지 못했습니다.');setFailed(true)}finally{setBusy(false)}}
 return <article className="detail-panel" aria-label={`${course.name} 상세 정보`}><div className="detail-top"><div className="eyebrow">{course.region} · COURSE {course.number}</div><button className="close-detail" aria-label="코스 정보 닫기" disabled={busy} onClick={onClose}><X size={20}/></button><h2>{course.name}</h2><div className="detail-stats"><span><Route size={17}/>{course.distance} km</span><span><Clock3 size={17}/>{duration(course.minutes)}</span><span className="difficulty">{course.difficulty}</span>{visit&&<span className="completed-label"><Check size={15}/>다녀온 길</span>}</div></div><div className="detail-body">
 <section className="detail-section"><h3>시점 · 종점 <span>스탬프 QR 위치</span></h3><div className="endpoint-grid"><div className="endpoint-column-label">코스 위치</div><div className="endpoint-column-label"><QrCode size={13}/>스탬프 QR 위치</div>{(['start','end'] as const).map((key,i)=><div className="endpoint-pair" key={key}><div><b className={`endpoint-label ${key}`}>{i===0?'시점':'종점'}</b><p>{course[key]||'원본 미제공'}</p></div><div><b className="qr-label"><QrCode size={13}/>{i===0?'시점 QR':'종점 QR'}</b><p>{course.stamp[key]||'원본에 위치 안내가 없습니다.'}</p></div></div>)}</div></section>
 <section className="detail-section"><h3>코스별 주요내용</h3><ul className="summary-list">{course.summary.length?course.summary.map((line,i)=><li key={i}>{line}</li>):<li>아래 주요지점과 원본 코스 안내를 확인해 주세요.</li>}</ul><h4>주요지점</h4><ol className="waypoints">{course.points.map((p,i)=><li key={i}><span className="waypoint-dot"/><div><strong>{p.name}</strong>{p.nextDistance&&<small>다음 지점까지 {p.nextDistance.replace(/km/i,' km')}</small>}</div></li>)}</ol><h4>편의시설</h4>{course.facilities.length?<dl className="facilities">{course.facilities.map((f,i)=><div key={i}><dt>{f.type}</dt><dd>{f.description}</dd></div>)}</dl>:course.facilityGuidance?.length?<><ul className="summary-list">{course.facilityGuidance.map((f,i)=><li key={i}>{f}</li>)}</ul><p className="small-note">두루누비 여행자 안내에 기재된 편의시설 정보입니다.</p></>:<p className="missing-info">원본에 편의시설 정보가 제공되지 않습니다.</p>}<h4><Mountain size={17}/>고도</h4><Elevation course={course}/></section>
 {course.warning&&<section className="detail-section"><h3>코스 이용 안내</h3><p className="warning">{course.warning}</p></section>}
 <section className="detail-section visit-section"><h3><BookmarkCheck size={18}/>다녀온 길 관리</h3><p className="small-note">방문일과 메모를 계정에 저장합니다. 날짜는 비워 두어도 됩니다.</p><form onSubmit={save}><label htmlFor="visited-on">방문일 <small>선택</small></label><input id="visited-on" type="date" value={date} onChange={e=>setDate(e.target.value)} disabled={busy||!available} max={new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}/><label htmlFor="visit-note">메모 <small>{note.length}/1,000</small></label><textarea id="visit-note" rows={3} value={note} maxLength={1000} placeholder="함께 걸은 사람, 기억에 남는 풍경…" onChange={e=>setNote(e.target.value)} disabled={busy||!available}/><div className="visit-actions"><button className="primary-button" type="submit" disabled={busy||!available}><Save size={16}/>{busy?'처리 중…':visit?'기록 수정':'다녀온 코스로 저장'}</button>{visit&&<button className="remove-button" type="button" onClick={remove} disabled={busy||!available} aria-label="이 코스의 방문 기록 삭제"><Trash2 size={16}/>삭제</button>}</div>{!available&&<p className="form-error">계정 기록이 연결되면 저장할 수 있습니다.</p>}<p className={failed?'form-error':'form-success'} role="status">{message}</p></form></section>
 <a className="detail-link" href={`https://www.durunubi.kr/course-detail-view.do?crs_idx=${encodeURIComponent(course.id)}`} target="_blank" rel="noreferrer">두루누비에서 최신 정보 보기<ArrowUpRight size={17}/></a><p className="small-note">자료: 두루누비 · 2026.09.07 기준</p></div></article>
}
